# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true

# ????????? Android Studio ?????? JDK (jbr-17)
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true

# ?????????????
org.gradle.configuration-cache=false